### ISSUE TITLE
TypeError: conversion from NoneType to Decimal is not supported

### ISSUE THREAD

**Issue by molecular** [OPReturnCode/TokenDex#1]
When I select OLI token and click "Order" button:
```
Traceback (most recent call last):
  File "/home/nick/.electron-cash-slp/external_plugins/TokenDex-0.01-beta.zip/TokenDex/ui.py", line 421, in place_order
    rate = PyDecimal(rate) / 10 ** 8
TypeError: conversion from NoneType to Decimal is not supported
```

Note that I wasn't able to fill `Token Amount` (greyed-out an prefilled with the amount of the coin I selected in `Select Coin`, `BCH amount` or`Rate` fields. They're all greyed out, so I just hit the `Order` button to see what would happen.

**Comment by OPReturnCode** [comment]
Thanks for the report. That error is fixed now ([v0.02-beta](https://github.com/OPReturnCode/TokenDex/releases/tag/v0.02-beta)).

`Token Amount` and `BCH Amount` are automatically populated after you select the coin you want to use for the order and enter the desired rate.

As for the `Rate`  field being greyed-out, I was not able to reproduce that. Can you maybe post a screenshot of the window if the issue still persisted for you?

**Comment by molecular** [comment]
Still can't fill "Token Amount", "BCH Amount". I *can* fill "rate".

![image](https://user-images.githubusercontent.com/589745/213861575-f5e8a1da-f29d-47a6-b817-20af1eab31d9.png)

no exception to be seen on stdout
